export const products = [
  {
    id: "lux-100-350",
    name: "Rolex Submariner",
    brand: "Rolex",
    serial: "LUX-100-350",
    owner: "Jérémy",
    tokenId: "0x4F2A...C891",
    materials: "Acier 904L · Saphir",
    price: 12500,
    verified: true,
    history: [
      { label: "Transfert de propriété", date: "Mars 2024" },
      { label: "Certification initiale", date: "Janv. 2022" },
      { label: "Fabrication & sortie usine", date: "Oct. 2021" },
    ],
  },
  {
    id: "lux-200-112",
    name: "Patek Philippe Nautilus",
    brand: "Patek Philippe",
    serial: "LUX-200-112",
    owner: "Jérémy",
    tokenId: "0x8B3D...A204",
    materials: "Or blanc 18k · Saphir",
    price: 38000,
    verified: true,
    history: [
      { label: "Transfert de propriété", date: "Juin 2023" },
      { label: "Certification initiale", date: "Fév. 2021" },
      { label: "Fabrication & sortie usine", date: "Nov. 2020" },
    ],
  },
  {
    id: "lux-310-078",
    name: "Hermès Birkin 30",
    brand: "Hermès",
    serial: "LUX-310-078",
    owner: "Jérémy",
    tokenId: "0x1C9F...E550",
    materials: "Cuir Togo · Palladium",
    price: 24000,
    verified: true,
    history: [
      { label: "Transfert de propriété", date: "Déc. 2023" },
      { label: "Certification initiale", date: "Avr. 2022" },
      { label: "Fabrication & sortie usine", date: "Jan. 2022" },
    ],
  },
]